name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run flake8
        run: flake8 src/*.py

  charity-api-key:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3
    - name: Use API Key
      run: |
        echo "API_KEY=${{ secrets.REGISTERED_CHARITIES_API_KEY }}" >> $GITHUB_ENV
    - name: test
      run: |
        url = "https://api.charitycommission.gov.uk/register/api/charityRegNumber/1053992/0"
        headers = {"Ocp-Apim-Subscription-Key":API_KEY}
        response = requests.get(url, headers=headers)
        charity_info = response.json()
        print("Hello " + charity_info["charity_name"])
    
  run-unit-tests:
    needs: charity-api-key
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Unit Tests
        run: pytest tests/*.py 

  deploy-to-vercel:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'